### PR TITLE
Build against system raylib

### PR DESCRIPTION
**Pull request by ehmry**
This makes it buildable on my machine without using the vendored raylib and avoids the hardcoded path at https://github.com/ehmry/naylib/blob/1d8b8c686167aed0bffa6cd35df590da70e6de6a/src/raylib.nim#L5

### CODE REVIEW

**Comment by planetis-m** [comment]
Thank you for this patch, I am really gratefull for working on this. However I am not sure I can merge it. For one

**Comment by ehmry** [comment]
Okay, I need dig into this more and run more tests then.

**Comment by planetis-m** [comment]
I've tried before using emit, but you need to place it in every module of your project that imports naylib:

```
{.emit: """/*INCLUDESECTION*/
#if defined(__WIN32) || defined(__WIN64)
#define WIN32_LEAN_AND_MEAN
#define Rectangle rectangle_win32
#define CloseWindow CloseWindow_win32
#define ShowCursor __imp_ShowCursor
#define _APISETSTRING_
#endif

#if defined(__WIN32) || defined(__WIN64)
#undef DrawText
#undef ShowCursor
#undef CloseWindow
#undef Rectangle
#endif
""".}
```

Clearly can't work.

**Comment by planetis-m** [comment]
Closing, reason: no response.

**Pull request closed without merging**
